### PR TITLE
Use iso3c for countries to reduce NAs in HDI

### PR DESCRIPTION
**Pull request by jmcastagnetto**
Looking at the dataset, I noticed that some countries had "NA" for the HDI because the names did not match exactly between the two original datasets. This can be fixed if we use the `countrycode` package to map the names to ISO3C codes. In the end the countryes in the `corruption` dataframe that do not have HDIs will be: "Taiwan" , "Kosovo" , "Korea (North)", "Somalia" (which aren't in the original data)

Also, there was a minor encoding issue that affected countries such as "Côte d'Ivoire", that was fixed using the "locale" option of `read_csv()`

### CODE REVIEW

**Comment by clauswilke** [comment]
Thanks. As far as I can see, the purpose of your patch is to modify the data frame that is distributed as part of the package. Could you rerun the patch top to bottom so the data frame is actually updated, and then commit the changed file? (It's going to be this one: https://github.com/wilkelab/practicalgg/blob/master/data/corruption.rda)

**Comment by jmcastagnetto** [comment]
Yes, the idea was that the dataset will contain as much info from HDI as possible.
Just re-run the script and the dataset file has been comited to the branch.

**Comment by clauswilke** [comment]
Thanks! I don't have automatic deployment to the website, so that will change only the next time I work on the package.

**Comment by jmcastagnetto** [comment]
Cool! no rush with the update. I may bother you in the future with a couple of viz ideas I got, but not in the near term, job is keeping me busy.

**Pull request merged**
